### ISSUE TITLE
Pumpkin pie missing from rmextract + recipe cannot be removed

### ISSUE THREAD

**Issue by Pilvinen** [haveric/RecipeManager2#47]
Using RecipeManager v2.6.4 for 1.8.1 Nov 04, 2015

Running rmextract is missing recipe for pumpkin pie.

And I tried to remove the recipe with:
combine // piirakan esto
@remove
pumpkin:0 + sugar:0 + egg:0
= pumpkin_pie:0:1

But it fails to remove the vanilla recipe.

**Comment by haveric** [comment]
I'm not at a dev machine, but I checked my files and it exported for me previously:
`combine
sugar:0 + egg:0 + pumpkin:0
= pumpkin_pie:0:1`

Are you sure another plugin isn't removing or modifying it first?

**Comment by Pilvinen** [comment]
Yes I am. I shouldn't have any other plugins that affect recipes as far as I know.

I suspect I am missing other recipes also from the extracted recipes file. I remember having similar trouble about a year ago.

Here, when you are on your dev machine you can do a diff on your version of the file and mine:

https://www.dropbox.com/s/l97og46kn56xxo5/extracted%20recipes%20%282016-02-15%2013-14-22%29.txt?dl=0

Perhaps you could link me extracted recipes file that is not missing anything? If you don't find what's causing this I would at least have a complete file to refer to.

**Comment by haveric** [comment]
Sending you a file generated on my machine won't help you as there is something configured on yours that is messing with recipes.

- Do you get the same output with only RecipeManager installed?
- What are your current configured recipes and settings? 
- Do you see any errors on startup?

**Comment by Pilvinen** [comment]
I made a new fresh test server, copied my installation of RecipeManager and ran rmextract.
The generated file is the same as the one from my production server.

So I am NOT getting recipe for pumpkin pie extracted on the test server that ONLY has RecipeManager installed. No errors.

I'm using Spigot, latest build (but this problem has been around at least 1,5 years.)

I made a zip of my whole recipemanager folder:
https://www.dropbox.com/s/vbv2hmyo5i1i9ge/recipemanager.zip?dl=0

Hope this helps in finding out what the problem is.

**Comment by haveric** [comment]
Two things:
1. Use rmextract before creating any recipes to get the full list of vanilla recipes.
2. @remove not working for combine recipes was a frustrating, yet simple bug. I just spent the last couple hours combing through code only to realize it was happening right away in the recipe processing. Also, this has somehow gone unnoticed since before I took over the plugin, so I'd like to thank you for reporting this.

There's a major update coming soon, but if you want a temporary solution, you can change @remove to @restrict. It has similar functionality, but will instead inform the user they can't craft the item, instead of removing it entirely.

**Comment by Pilvinen** [comment]
Glad to be of help. Thanks.

**Comment by haveric** [comment]
This has been fixed in 2.7
