### ISSUE TITLE
Serious duplication issue with 2.7

### ISSUE THREAD

**Issue by Pilvinen** [haveric/RecipeManager2#51]
Shift-clicking will give you infinite amounts of items without using any of the ingredients.

Example recipe (but you get the bug with all RecipeManager custom recipes):

craft
wool:* + wool:* + wool:*
raw_fish:3 + raw_fish:3 + raw_fish:3
wood:* + wood:* + wood:*
= slime_block:0:1

**Comment by haveric** [comment]
I'm not able to replicate this. Are you able to replicate this with only RecipeManager installed? If so, can you provide your full list of recipes? 

What version of Bukkit/Spigot are you running?
Do you get any errors in the console on startup or when creating the recipe?

**Comment by Pilvinen** [comment]
No errors. No plugins affecting recipes.

RecipeManager 1.6.4 works as intended with my recipes and config -> after updating to 1.7 the bug appears. Nothing else has changed except the version. The bug only happens when you **shift click **when crafting. You can just hold shift and keep clicking on the result slot and you get infinite items and it's not only a client side bug, you actually get the items.

/version gives: "This server is running CraftBukkit version git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)"

You can use my full list of recipes from this closed issue here, they haven't changed since then:
https://github.com/haveric/RecipeManager2/issues/47

**Comment by haveric** [comment]
The "@keepitem potion | replace bottle" at the top of the shaped.txt file is tripping it up for some reason. Remove that and the recipes work as normal.

I'm not sure offhand why keepitem is breaking it with an item that isn't in the recipe so I'll be looking into that, but also realize that because the flag is at the top, it is being added to all recipes in that file, not just the ones with those ingredients.
