### ISSUE TITLE
RecipeManager incorrectly tags duplicate recipes

### ISSUE THREAD

**Issue by GiovanH** [haveric/RecipeManager2#77]
RecipeManager is reporting an error, 
`Fatal: Recipe already created with this plugin`
with a file like this;

````
COMBINE Cash Chicken
Skull:3:1
= FEATHER:0:64
@ingredientcondition Skull | lore "Chicken Head"
@command /summon Item {x} {y} {z} {Item:{id:chicken,Count:64}}

COMBINE Cash Cow
Skull:3:1
= LEATHER:0:64
@ingredientcondition Skull | lore "Cow Head"
@command /summon Item {x} {y} {z} {Item:{id:beef,Count:64}}
````

Of course, it is not intended for a skull to match both of these conditions at once. However, recipemanager does not consider the @ingredientcondition tag, and marks the second recipe as a repeat of the first.

**Comment by GiovanH** [comment]
A possible solution to this would be adding a "Head Owner" ingredientcondition.

**Comment by haveric** [comment]
You can't have two recipes which use the same ingredients. Minecraft doesn't know about all the extra flags that RecipeManager is adding, so it can only tell the difference based on ingredients. RecipeManager's solution is to combine the recipes together using @individualresults and chaining the results after each other so that it acts as a single recipe to Minecraft, but leverages the conditions for multiple results.

Try the following:

````COMBINE Cash Chicken
@individualresults
Skull:3:1
= FEATHER:0:64
@ingredientcondition Skull | lore "Chicken Head"
@command /summon Item {x} {y} {z} {Item:{id:chicken,Count:64}}
= LEATHER:0:64
@ingredientcondition Skull | lore "Cow Head"
@command /summon Item {x} {y} {z} {Item:{id:beef,Count:64}}
