### ISSUE TITLE
Is the plugin in a compilable state? Is there a trick to building it?

### ISSUE THREAD

**Issue by totemo** [haveric/RecipeManager2#86]
From the recent commits it certainly seems like this project should build but I haven't had any luck building it.

I have Gradle 5.5.1 (latest) installed and in the path.

I cloned RecipeManagerCommand and ran `gradle build`. That was fine.

Then I `git clone --recursive https://github.com/haveric/RecipeManager2`, `cd RecipeManager2` and `gradle build` and I get a ton of errors. (Transcript attached.)

It seems like I have everything I need in my local Maven repository:

```
$ ls ~/.m2/repository/org/spigotmc/spigot/
1.10.2-R0.1-SNAPSHOT/  1.13.2-R0.1-SNAPSHOT/     1.8.7-R0.1-SNAPSHOT/
1.10-R0.1-SNAPSHOT/    1.13-pre7-R0.1-SNAPSHOT/  1.8.8-R0.1-SNAPSHOT/
1.11.2-R0.1-SNAPSHOT/  1.13-R0.1-SNAPSHOT/       1.8-R0.1-SNAPSHOT/
1.11-R0.1-SNAPSHOT/    1.14.3-R0.1-SNAPSHOT/     1.9.0-R0.1-SNAPSHOT/
1.12.1-R0.1-SNAPSHOT/  1.14.4-R0.1-SNAPSHOT/     1.9.2-R0.1-SNAPSHOT/
1.12.2-R0.1-SNAPSHOT/  1.14-R0.1-SNAPSHOT/       1.9.4-R0.1-SNAPSHOT/
1.12-pre6-SNAPSHOT/    1.8.3-R0.1-SNAPSHOT/      1.9-R0.1-SNAPSHOT/
1.12-R0.1-SNAPSHOT/    1.8.5-R0.1-SNAPSHOT/      1.9-SNAPSHOT/
1.13.1-R0.1-SNAPSHOT/  1.8.6-R0.1-SNAPSHOT/      maven-metadata-local.xml
```

I've built all of those versions with Spigot BuildTools.

What am I doing wrong?

[fail.txt](https://github.com/haveric/RecipeManager2/files/3427559/fail.txt)

**Comment by haveric** [comment]
Due to the complexity of supporting multiple NMS versions, the latest relies on having 3 different spigot jars included (and some potential manual mapping of bukkit after, but may depend on your environment). You should be able to get these jars by running `gradle libs`. This was the only way I could find to get it all to work and I'll be the first to admit that I don't like how complicated it has become to build. After the compatibility release coming up, I'll probably be dropping legacy support to help with this.

**Comment by totemo** [comment]
Not to worry I know the feeling. I will try `gradle libs`. Thanks a lot.

**Comment by haveric** [comment]
Have you made any progress or are you still stuck?

**Comment by totemo** [comment]
Oh. Sorry yes I can confirm that this allows me to build the plugin from source.
