### ISSUE TITLE
Make it look beautiful.

### ISSUE THREAD

**Issue by asdf80730** [haveric/RecipeManager2#95]
Can you add a space between [] when display recipebook's shape?
thanks and sorry for my poor english.
[a][b][c]
[d][][e]
[f][g][h]
↓↓↓↓↓↓↓↓
[a][b][c]
[d][ ][e]
[f][g][h]

**Comment by haveric** [comment]
Dev build with this fix can be found [here](https://cdn.discordapp.com/attachments/605797523935985686/719416629376843848/RecipeManager.jar) or referenced on the rm-devbuilds channel in [discord](https://discord.com/invite/3JY9JC3). Please let me know if you have a chance to test it and feel free to reopen if your issue is not resolved.
